function createfigure(X1, Y1, yvector1)
%CREATEFIGURE(X1,Y1,YVECTOR1)
%  X1:  stairs x
%  Y1:  stairs y
%  YVECTOR1:  area yvector

%  Auto-generated by MATLAB on 08-Feb-2018 09:19:05

% Create figure
figure1 = figure('XVisual',...
    '0xaa (TrueColor, depth 32, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.13 0.11 0.775 0.792380952380953]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 1]);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'all');

% Create stairs
stairs(X1,Y1,'Parent',axes1,'DisplayName','sinusoīda','Color',[0 0 0]);

% Create xlabel
xlabel('t,s');

% Create ylabel
ylabel('U,V');

% Create title
title('Mans 1. grafiks');

% Create area
area(X1,yvector1,'LineWidth',3,'LineStyle',':',...
    'FaceColor',[0.168627455830574 0.505882382392883 0.337254911661148],...
    'Parent',axes1,...
    'DisplayName','kosinusoīda');

% Create legend
legend(axes1,'show');

